options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/legal-qa-frontend',
      '--build-arg', 'VITE_API_URL=https://ai-lawyers-influencers-809263430963.us-central1.run.app',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/legal-qa-frontend'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'legal-qa-frontend',
      '--image', 'gcr.io/$PROJECT_ID/legal-qa-frontend',
      '--region', 'us-central1',
      '--port',  '8080',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/legal-qa-frontend'


